export type ResumeDeatilsFormData = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  dateOfBirth?: string;
professionalSummary?: string;
  professionalSummaryTITLE: string;
  emplymentTITLE: string;
  socialLinksTITLE: string;
  skillsTITLE: string;
  city?: string;
  address?: string;
  employmentHistory?: string;
  education?: string;
  photo?: string;
  socialLinks?: Array<string>;
  skills?: Array<string>;
  age?: number;
};
